live_config_reload = true
shell = "tmux"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[[colors.indexed_colors]]
color = "0xff966c"
index = 16

[[colors.indexed_colors]]
color = "0xc53b53"
index = 17

[colors.bright]
black = "0x444a73"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0xc8d3f5"
yellow = "0xffc777"

[colors.normal]
black = "0x1b1d2b"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0x828bb8"
yellow = "0xffc777"

[colors.primary]
background = "0x222436"
foreground = "0xc8d3f5"

[cursor]
thickness = 0.3
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
size = 10

[font.normal]
family = "JetBrainsMono NF"
style = "Medium"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0
